/*
 * This source file was generated by the Gradle 'init' task
 */
package spring.localstorage.crud.ui;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        LocalStorageUiApplication classUnderTest = new LocalStorageUiApplication();
        assertNotNull( "app should have a greeting");
    }
}
